/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventCertificatesGetV3EventIdCertificates } from "../../funcs/eventCertificatesGetV3EventIdCertificates.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV3EventIdCertificatesRequest$inboundSchema,
};

export const tool$eventCertificatesGetV3EventIdCertificates: ToolDefinition<
  typeof args
> = {
  name: "event-certificates_get-v3-event-id-certificates",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventCertificatesGetV3EventIdCertificates(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
