/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventProductVariantsDeleteV3EventsEventIdProductsProductIdVariantsId } from "../../funcs/eventProductVariantsDeleteV3EventsEventIdProductsProductIdVariantsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .DeleteV3EventsEventIdProductsProductIdVariantsIdRequest$inboundSchema,
};

export const tool$eventProductVariantsDeleteV3EventsEventIdProductsProductIdVariantsId:
  ToolDefinition<typeof args> = {
    name:
      "event-product-variants_delete-v3-events-event-id-products-product-id-variants-id",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await eventProductVariantsDeleteV3EventsEventIdProductsProductIdVariantsId(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
