/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsPostV3Events } from "../../funcs/eventsPostV3Events.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostV3EventsRequest$inboundSchema,
};

export const tool$eventsPostV3Events: ToolDefinition<typeof args> = {
  name: "events_post-v3-events",
  description: `Creates a new event.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsPostV3Events(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
