/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventCollectionDeleteV3EventcollectionsId } from "../../funcs/eventCollectionDeleteV3EventcollectionsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteV3EventcollectionsIdRequest$inboundSchema,
};

export const tool$eventCollectionDeleteV3EventcollectionsId: ToolDefinition<
  typeof args
> = {
  name: "event-collection_delete-v3-eventcollections-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventCollectionDeleteV3EventcollectionsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
