/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventCertificatesGetV3EventIdCertificatesPreview } from "../../funcs/eventCertificatesGetV3EventIdCertificatesPreview.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV3EventIdCertificatesPreviewRequest$inboundSchema,
};

export const tool$eventCertificatesGetV3EventIdCertificatesPreview:
  ToolDefinition<typeof args> = {
    name: "event-certificates_get-v3-event-id-certificates-preview",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await eventCertificatesGetV3EventIdCertificatesPreview(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
