/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventCollectionGetV3EventcollectionsId } from "../../funcs/eventCollectionGetV3EventcollectionsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV3EventcollectionsIdRequest$inboundSchema,
};

export const tool$eventCollectionGetV3EventcollectionsId: ToolDefinition<
  typeof args
> = {
  name: "event-collection_get-v3-eventcollections-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventCollectionGetV3EventcollectionsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
