/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationsQueueingPostV3NotificationsSms } from "../../funcs/notificationsQueueingPostV3NotificationsSms.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostV3NotificationsSmsRequest$inboundSchema,
};

export const tool$notificationsQueueingPostV3NotificationsSms: ToolDefinition<
  typeof args
> = {
  name: "notifications-queueing_post-v3-notifications-sms",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notificationsQueueingPostV3NotificationsSms(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
