/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { onlineCourseGetV3OnlinecoursesId } from "../../funcs/onlineCourseGetV3OnlinecoursesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV3OnlinecoursesIdRequest$inboundSchema,
};

export const tool$onlineCourseGetV3OnlinecoursesId: ToolDefinition<
  typeof args
> = {
  name: "online-course_get-v3-onlinecourses-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await onlineCourseGetV3OnlinecoursesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
