/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersPatchV3OrdersId } from "../../funcs/ordersPatchV3OrdersId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PatchV3OrdersIdRequest$inboundSchema,
};

export const tool$ordersPatchV3OrdersId: ToolDefinition<typeof args> = {
  name: "orders_patch-v3-orders-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ordersPatchV3OrdersId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
