/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsPostV3Organizations } from "../../funcs/organizationsPostV3Organizations.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostV3OrganizationsRequest$inboundSchema,
};

export const tool$organizationsPostV3Organizations: ToolDefinition<
  typeof args
> = {
  name: "organizations_post-v3-organizations",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationsPostV3Organizations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
