/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationSettingsPutV3OrganizationsOrganizationIdSettings } from "../../funcs/organizationSettingsPutV3OrganizationsOrganizationIdSettings.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.PutV3OrganizationsOrganizationIdSettingsRequest$inboundSchema,
};

export const tool$organizationSettingsPutV3OrganizationsOrganizationIdSettings:
  ToolDefinition<typeof args> = {
    name: "organization-settings_put-v3-organizations-organization-id-settings",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await organizationSettingsPutV3OrganizationsOrganizationIdSettings(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
