/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { registrationsPostV3Registrations } from "../../funcs/registrationsPostV3Registrations.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostV3RegistrationsRequest$inboundSchema,
};

export const tool$registrationsPostV3Registrations: ToolDefinition<
  typeof args
> = {
  name: "registrations_post-v3-registrations",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await registrationsPostV3Registrations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
