/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PaymentProvider,
  PaymentProvider$inboundSchema,
  PaymentProvider$outboundSchema,
} from "./paymentprovider.js";
import {
  RegistrationCustomerInfoDto,
  RegistrationCustomerInfoDto$inboundSchema,
  RegistrationCustomerInfoDto$Outbound,
  RegistrationCustomerInfoDto$outboundSchema,
} from "./registrationcustomerinfodto.js";
import {
  RegistrationType,
  RegistrationType$inboundSchema,
  RegistrationType$outboundSchema,
} from "./registrationtype.js";

export type NewRegistrationDto = {
  customer?: RegistrationCustomerInfoDto | undefined;
  notes?: string | null | undefined;
  type?: RegistrationType | undefined;
  paymentMethod?: PaymentProvider | undefined;
  userId: string;
  eventId: number;
  createOrder?: boolean | undefined;
  sendWelcomeLetter?: boolean | undefined;
};

/** @internal */
export const NewRegistrationDto$inboundSchema: z.ZodType<
  NewRegistrationDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer: RegistrationCustomerInfoDto$inboundSchema.optional(),
  notes: z.nullable(z.string()).optional(),
  type: RegistrationType$inboundSchema.optional(),
  paymentMethod: PaymentProvider$inboundSchema.optional(),
  userId: z.string(),
  eventId: z.number().int(),
  createOrder: z.boolean().optional(),
  sendWelcomeLetter: z.boolean().optional(),
});

/** @internal */
export type NewRegistrationDto$Outbound = {
  customer?: RegistrationCustomerInfoDto$Outbound | undefined;
  notes?: string | null | undefined;
  type?: string | undefined;
  paymentMethod?: string | undefined;
  userId: string;
  eventId: number;
  createOrder?: boolean | undefined;
  sendWelcomeLetter?: boolean | undefined;
};

/** @internal */
export const NewRegistrationDto$outboundSchema: z.ZodType<
  NewRegistrationDto$Outbound,
  z.ZodTypeDef,
  NewRegistrationDto
> = z.object({
  customer: RegistrationCustomerInfoDto$outboundSchema.optional(),
  notes: z.nullable(z.string()).optional(),
  type: RegistrationType$outboundSchema.optional(),
  paymentMethod: PaymentProvider$outboundSchema.optional(),
  userId: z.string(),
  eventId: z.number().int(),
  createOrder: z.boolean().optional(),
  sendWelcomeLetter: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NewRegistrationDto$ {
  /** @deprecated use `NewRegistrationDto$inboundSchema` instead. */
  export const inboundSchema = NewRegistrationDto$inboundSchema;
  /** @deprecated use `NewRegistrationDto$outboundSchema` instead. */
  export const outboundSchema = NewRegistrationDto$outboundSchema;
  /** @deprecated use `NewRegistrationDto$Outbound` instead. */
  export type Outbound = NewRegistrationDto$Outbound;
}

export function newRegistrationDtoToJSON(
  newRegistrationDto: NewRegistrationDto,
): string {
  return JSON.stringify(
    NewRegistrationDto$outboundSchema.parse(newRegistrationDto),
  );
}

export function newRegistrationDtoFromJSON(
  jsonString: string,
): SafeParseResult<NewRegistrationDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NewRegistrationDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NewRegistrationDto' from JSON`,
  );
}
