/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const NotificationType = {
  Email: "Email",
  Sms: "Sms",
} as const;
export type NotificationType = ClosedEnum<typeof NotificationType>;

/** @internal */
export const NotificationType$inboundSchema: z.ZodNativeEnum<
  typeof NotificationType
> = z.nativeEnum(NotificationType);

/** @internal */
export const NotificationType$outboundSchema: z.ZodNativeEnum<
  typeof NotificationType
> = NotificationType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationType$ {
  /** @deprecated use `NotificationType$inboundSchema` instead. */
  export const inboundSchema = NotificationType$inboundSchema;
  /** @deprecated use `NotificationType$outboundSchema` instead. */
  export const outboundSchema = NotificationType$outboundSchema;
}
