/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const OrganizationSettingType = {
  String: "String",
  Number: "Number",
  Url: "Url",
  Email: "Email",
  Boolean: "Boolean",
} as const;
export type OrganizationSettingType = ClosedEnum<
  typeof OrganizationSettingType
>;

/** @internal */
export const OrganizationSettingType$inboundSchema: z.ZodNativeEnum<
  typeof OrganizationSettingType
> = z.nativeEnum(OrganizationSettingType);

/** @internal */
export const OrganizationSettingType$outboundSchema: z.ZodNativeEnum<
  typeof OrganizationSettingType
> = OrganizationSettingType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationSettingType$ {
  /** @deprecated use `OrganizationSettingType$inboundSchema` instead. */
  export const inboundSchema = OrganizationSettingType$inboundSchema;
  /** @deprecated use `OrganizationSettingType$outboundSchema` instead. */
  export const outboundSchema = OrganizationSettingType$outboundSchema;
}
