/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type OrganizationFormDto = {
  name: string;
  description?: string | null | undefined;
  url?: string | null | undefined;
  phone?: string | null | undefined;
  email?: string | null | undefined;
  logoUrl?: string | null | undefined;
  logoBase64?: string | null | undefined;
};

/** @internal */
export const OrganizationFormDto$inboundSchema: z.ZodType<
  OrganizationFormDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
  phone: z.nullable(z.string()).optional(),
  email: z.nullable(z.string()).optional(),
  logoUrl: z.nullable(z.string()).optional(),
  logoBase64: z.nullable(z.string()).optional(),
});

/** @internal */
export type OrganizationFormDto$Outbound = {
  name: string;
  description?: string | null | undefined;
  url?: string | null | undefined;
  phone?: string | null | undefined;
  email?: string | null | undefined;
  logoUrl?: string | null | undefined;
  logoBase64?: string | null | undefined;
};

/** @internal */
export const OrganizationFormDto$outboundSchema: z.ZodType<
  OrganizationFormDto$Outbound,
  z.ZodTypeDef,
  OrganizationFormDto
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
  phone: z.nullable(z.string()).optional(),
  email: z.nullable(z.string()).optional(),
  logoUrl: z.nullable(z.string()).optional(),
  logoBase64: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationFormDto$ {
  /** @deprecated use `OrganizationFormDto$inboundSchema` instead. */
  export const inboundSchema = OrganizationFormDto$inboundSchema;
  /** @deprecated use `OrganizationFormDto$outboundSchema` instead. */
  export const outboundSchema = OrganizationFormDto$outboundSchema;
  /** @deprecated use `OrganizationFormDto$Outbound` instead. */
  export type Outbound = OrganizationFormDto$Outbound;
}

export function organizationFormDtoToJSON(
  organizationFormDto: OrganizationFormDto,
): string {
  return JSON.stringify(
    OrganizationFormDto$outboundSchema.parse(organizationFormDto),
  );
}

export function organizationFormDtoFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationFormDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationFormDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationFormDto' from JSON`,
  );
}
