/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ProductDto,
  ProductDto$inboundSchema,
  ProductDto$Outbound,
  ProductDto$outboundSchema,
} from "./productdto.js";
import {
  ProductVariantDto,
  ProductVariantDto$inboundSchema,
  ProductVariantDto$Outbound,
  ProductVariantDto$outboundSchema,
} from "./productvariantdto.js";

export type ProductOrderDto = {
  productId?: number | undefined;
  productVariantId?: number | null | undefined;
  product?: ProductDto | undefined;
  productVariant?: ProductVariantDto | undefined;
  quantity?: number | undefined;
};

/** @internal */
export const ProductOrderDto$inboundSchema: z.ZodType<
  ProductOrderDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  productId: z.number().int().optional(),
  productVariantId: z.nullable(z.number().int()).optional(),
  product: ProductDto$inboundSchema.optional(),
  productVariant: ProductVariantDto$inboundSchema.optional(),
  quantity: z.number().int().optional(),
});

/** @internal */
export type ProductOrderDto$Outbound = {
  productId?: number | undefined;
  productVariantId?: number | null | undefined;
  product?: ProductDto$Outbound | undefined;
  productVariant?: ProductVariantDto$Outbound | undefined;
  quantity?: number | undefined;
};

/** @internal */
export const ProductOrderDto$outboundSchema: z.ZodType<
  ProductOrderDto$Outbound,
  z.ZodTypeDef,
  ProductOrderDto
> = z.object({
  productId: z.number().int().optional(),
  productVariantId: z.nullable(z.number().int()).optional(),
  product: ProductDto$outboundSchema.optional(),
  productVariant: ProductVariantDto$outboundSchema.optional(),
  quantity: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductOrderDto$ {
  /** @deprecated use `ProductOrderDto$inboundSchema` instead. */
  export const inboundSchema = ProductOrderDto$inboundSchema;
  /** @deprecated use `ProductOrderDto$outboundSchema` instead. */
  export const outboundSchema = ProductOrderDto$outboundSchema;
  /** @deprecated use `ProductOrderDto$Outbound` instead. */
  export type Outbound = ProductOrderDto$Outbound;
}

export function productOrderDtoToJSON(
  productOrderDto: ProductOrderDto,
): string {
  return JSON.stringify(ProductOrderDto$outboundSchema.parse(productOrderDto));
}

export function productOrderDtoFromJSON(
  jsonString: string,
): SafeParseResult<ProductOrderDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductOrderDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductOrderDto' from JSON`,
  );
}
