services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Historia
      args:
        CMS_SECRET: secret
    container_name: historia_app
    environment:
      - CMS_SECRET=secret
      - DATABASE_URL=file:./historia.db
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on: [db]

  db:
    image: postgres:15
    container_name: historia_db
    environment:
      POSTGRES_USER: historia
      POSTGRES_PASSWORD: password
      POSTGRES_DB: historia
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
