# Get dependencies
FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/web/package.json ./apps/web/
COPY libs/datatable/package.json ./libs/datatable/
COPY libs/eslint-config/package.json ./libs/eslint-config/
COPY libs/forms/package.json ./libs/forms/
COPY libs/markdown/package.json ./libs/markdown/
COPY libs/markdowninput/package.json ./libs/markdowninput/
COPY libs/registrations-sdk/package.json ./libs/registrations-sdk/
COPY libs/scribo/package.json ./libs/scribo/
COPY libs/sdk/package.json ./libs/sdk/
COPY libs/smartform/package.json ./libs/smartform/
COPY libs/typescript-config/package.json ./libs/typescript-config/
COPY libs/ui/package.json ./libs/ui/
COPY libs/utils/package.json ./libs/utils/
RUN npm ci

# Build next.js
FROM node:22-bookworm-slim AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN npx turbo build

# Copy to production image
FROM node:22-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV production

# COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app/.next
USER nextjs

EXPOSE 3000
RUN npx next telemetry disable

CMD ["node_modules/.bin/next", "start"]
