/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV3OrganizationsOrganizationIdMembersUserIdRequest = {
  organizationId: number;
  userId: string;
  /**
   * Optional organization Id. Will be required in API version 4.
   */
  eventurasOrgId?: number | undefined;
};

/** @internal */
export const DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$inboundSchema:
  z.ZodType<
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    organizationId: z.number().int(),
    userId: z.string(),
    "Eventuras-Org-Id": z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      "Eventuras-Org-Id": "eventurasOrgId",
    });
  });

/** @internal */
export type DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$Outbound = {
  organizationId: number;
  userId: string;
  "Eventuras-Org-Id"?: number | undefined;
};

/** @internal */
export const DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$outboundSchema:
  z.ZodType<
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$Outbound,
    z.ZodTypeDef,
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest
  > = z.object({
    organizationId: z.number().int(),
    userId: z.string(),
    eventurasOrgId: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      eventurasOrgId: "Eventuras-Org-Id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$ {
  /** @deprecated use `DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$inboundSchema;
  /** @deprecated use `DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$outboundSchema;
  /** @deprecated use `DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$Outbound` instead. */
  export type Outbound =
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$Outbound;
}

export function deleteV3OrganizationsOrganizationIdMembersUserIdRequestToJSON(
  deleteV3OrganizationsOrganizationIdMembersUserIdRequest:
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest,
): string {
  return JSON.stringify(
    DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$outboundSchema
      .parse(deleteV3OrganizationsOrganizationIdMembersUserIdRequest),
  );
}

export function deleteV3OrganizationsOrganizationIdMembersUserIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteV3OrganizationsOrganizationIdMembersUserIdRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteV3OrganizationsOrganizationIdMembersUserIdRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteV3OrganizationsOrganizationIdMembersUserIdRequest' from JSON`,
  );
}
