/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV3NotificationsIdRequest = {
  id: number;
  includeStatistics?: boolean | undefined;
  /**
   * Optional organization Id. Will be required in API version 4.
   */
  eventurasOrgId?: number | undefined;
};

/** @internal */
export const GetV3NotificationsIdRequest$inboundSchema: z.ZodType<
  GetV3NotificationsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  includeStatistics: z.boolean().default(false),
  "Eventuras-Org-Id": z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "Eventuras-Org-Id": "eventurasOrgId",
  });
});

/** @internal */
export type GetV3NotificationsIdRequest$Outbound = {
  id: number;
  includeStatistics: boolean;
  "Eventuras-Org-Id"?: number | undefined;
};

/** @internal */
export const GetV3NotificationsIdRequest$outboundSchema: z.ZodType<
  GetV3NotificationsIdRequest$Outbound,
  z.ZodTypeDef,
  GetV3NotificationsIdRequest
> = z.object({
  id: z.number().int(),
  includeStatistics: z.boolean().default(false),
  eventurasOrgId: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    eventurasOrgId: "Eventuras-Org-Id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV3NotificationsIdRequest$ {
  /** @deprecated use `GetV3NotificationsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetV3NotificationsIdRequest$inboundSchema;
  /** @deprecated use `GetV3NotificationsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetV3NotificationsIdRequest$outboundSchema;
  /** @deprecated use `GetV3NotificationsIdRequest$Outbound` instead. */
  export type Outbound = GetV3NotificationsIdRequest$Outbound;
}

export function getV3NotificationsIdRequestToJSON(
  getV3NotificationsIdRequest: GetV3NotificationsIdRequest,
): string {
  return JSON.stringify(
    GetV3NotificationsIdRequest$outboundSchema.parse(
      getV3NotificationsIdRequest,
    ),
  );
}

export function getV3NotificationsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV3NotificationsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3NotificationsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3NotificationsIdRequest' from JSON`,
  );
}
