/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV3EventIdCertificatesRequest = {
  id: number;
  page?: number | undefined;
  count?: number | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  ordering?: Array<string> | undefined;
  /**
   * Optional organization Id. Will be required in API version 4.
   */
  eventurasOrgId?: number | undefined;
};

/** @internal */
export const GetV3EventIdCertificatesRequest$inboundSchema: z.ZodType<
  GetV3EventIdCertificatesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  Page: z.number().int().optional(),
  Count: z.number().int().optional(),
  Limit: z.number().int().optional(),
  Offset: z.number().int().optional(),
  Ordering: z.array(z.string()).optional(),
  "Eventuras-Org-Id": z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "Page": "page",
    "Count": "count",
    "Limit": "limit",
    "Offset": "offset",
    "Ordering": "ordering",
    "Eventuras-Org-Id": "eventurasOrgId",
  });
});

/** @internal */
export type GetV3EventIdCertificatesRequest$Outbound = {
  id: number;
  Page?: number | undefined;
  Count?: number | undefined;
  Limit?: number | undefined;
  Offset?: number | undefined;
  Ordering?: Array<string> | undefined;
  "Eventuras-Org-Id"?: number | undefined;
};

/** @internal */
export const GetV3EventIdCertificatesRequest$outboundSchema: z.ZodType<
  GetV3EventIdCertificatesRequest$Outbound,
  z.ZodTypeDef,
  GetV3EventIdCertificatesRequest
> = z.object({
  id: z.number().int(),
  page: z.number().int().optional(),
  count: z.number().int().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  ordering: z.array(z.string()).optional(),
  eventurasOrgId: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    page: "Page",
    count: "Count",
    limit: "Limit",
    offset: "Offset",
    ordering: "Ordering",
    eventurasOrgId: "Eventuras-Org-Id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV3EventIdCertificatesRequest$ {
  /** @deprecated use `GetV3EventIdCertificatesRequest$inboundSchema` instead. */
  export const inboundSchema = GetV3EventIdCertificatesRequest$inboundSchema;
  /** @deprecated use `GetV3EventIdCertificatesRequest$outboundSchema` instead. */
  export const outboundSchema = GetV3EventIdCertificatesRequest$outboundSchema;
  /** @deprecated use `GetV3EventIdCertificatesRequest$Outbound` instead. */
  export type Outbound = GetV3EventIdCertificatesRequest$Outbound;
}

export function getV3EventIdCertificatesRequestToJSON(
  getV3EventIdCertificatesRequest: GetV3EventIdCertificatesRequest,
): string {
  return JSON.stringify(
    GetV3EventIdCertificatesRequest$outboundSchema.parse(
      getV3EventIdCertificatesRequest,
    ),
  );
}

export function getV3EventIdCertificatesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV3EventIdCertificatesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3EventIdCertificatesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3EventIdCertificatesRequest' from JSON`,
  );
}
