/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV3EventIdCertificatesIssueRequest = {
  id: number;
  send?: boolean | undefined;
  /**
   * Optional organization Id. Will be required in API version 4.
   */
  eventurasOrgId?: number | undefined;
};

/** @internal */
export const PostV3EventIdCertificatesIssueRequest$inboundSchema: z.ZodType<
  PostV3EventIdCertificatesIssueRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  send: z.boolean().default(true),
  "Eventuras-Org-Id": z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "Eventuras-Org-Id": "eventurasOrgId",
  });
});

/** @internal */
export type PostV3EventIdCertificatesIssueRequest$Outbound = {
  id: number;
  send: boolean;
  "Eventuras-Org-Id"?: number | undefined;
};

/** @internal */
export const PostV3EventIdCertificatesIssueRequest$outboundSchema: z.ZodType<
  PostV3EventIdCertificatesIssueRequest$Outbound,
  z.ZodTypeDef,
  PostV3EventIdCertificatesIssueRequest
> = z.object({
  id: z.number().int(),
  send: z.boolean().default(true),
  eventurasOrgId: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    eventurasOrgId: "Eventuras-Org-Id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV3EventIdCertificatesIssueRequest$ {
  /** @deprecated use `PostV3EventIdCertificatesIssueRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostV3EventIdCertificatesIssueRequest$inboundSchema;
  /** @deprecated use `PostV3EventIdCertificatesIssueRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostV3EventIdCertificatesIssueRequest$outboundSchema;
  /** @deprecated use `PostV3EventIdCertificatesIssueRequest$Outbound` instead. */
  export type Outbound = PostV3EventIdCertificatesIssueRequest$Outbound;
}

export function postV3EventIdCertificatesIssueRequestToJSON(
  postV3EventIdCertificatesIssueRequest: PostV3EventIdCertificatesIssueRequest,
): string {
  return JSON.stringify(
    PostV3EventIdCertificatesIssueRequest$outboundSchema.parse(
      postV3EventIdCertificatesIssueRequest,
    ),
  );
}

export function postV3EventIdCertificatesIssueRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostV3EventIdCertificatesIssueRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV3EventIdCertificatesIssueRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV3EventIdCertificatesIssueRequest' from JSON`,
  );
}
