/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV3OrganizationsOrganizationIdSettingsRequest = {
  organizationId: number;
  /**
   * Optional organization Id. Will be required in API version 4.
   */
  eventurasOrgId?: number | undefined;
  requestBody: Array<components.OrganizationSettingValueDto>;
};

/** @internal */
export const PostV3OrganizationsOrganizationIdSettingsRequest$inboundSchema:
  z.ZodType<
    PostV3OrganizationsOrganizationIdSettingsRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    organizationId: z.number().int(),
    "Eventuras-Org-Id": z.number().int().optional(),
    RequestBody: z.array(components.OrganizationSettingValueDto$inboundSchema),
  }).transform((v) => {
    return remap$(v, {
      "Eventuras-Org-Id": "eventurasOrgId",
      "RequestBody": "requestBody",
    });
  });

/** @internal */
export type PostV3OrganizationsOrganizationIdSettingsRequest$Outbound = {
  organizationId: number;
  "Eventuras-Org-Id"?: number | undefined;
  RequestBody: Array<components.OrganizationSettingValueDto$Outbound>;
};

/** @internal */
export const PostV3OrganizationsOrganizationIdSettingsRequest$outboundSchema:
  z.ZodType<
    PostV3OrganizationsOrganizationIdSettingsRequest$Outbound,
    z.ZodTypeDef,
    PostV3OrganizationsOrganizationIdSettingsRequest
  > = z.object({
    organizationId: z.number().int(),
    eventurasOrgId: z.number().int().optional(),
    requestBody: z.array(components.OrganizationSettingValueDto$outboundSchema),
  }).transform((v) => {
    return remap$(v, {
      eventurasOrgId: "Eventuras-Org-Id",
      requestBody: "RequestBody",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV3OrganizationsOrganizationIdSettingsRequest$ {
  /** @deprecated use `PostV3OrganizationsOrganizationIdSettingsRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostV3OrganizationsOrganizationIdSettingsRequest$inboundSchema;
  /** @deprecated use `PostV3OrganizationsOrganizationIdSettingsRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostV3OrganizationsOrganizationIdSettingsRequest$outboundSchema;
  /** @deprecated use `PostV3OrganizationsOrganizationIdSettingsRequest$Outbound` instead. */
  export type Outbound =
    PostV3OrganizationsOrganizationIdSettingsRequest$Outbound;
}

export function postV3OrganizationsOrganizationIdSettingsRequestToJSON(
  postV3OrganizationsOrganizationIdSettingsRequest:
    PostV3OrganizationsOrganizationIdSettingsRequest,
): string {
  return JSON.stringify(
    PostV3OrganizationsOrganizationIdSettingsRequest$outboundSchema.parse(
      postV3OrganizationsOrganizationIdSettingsRequest,
    ),
  );
}

export function postV3OrganizationsOrganizationIdSettingsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV3OrganizationsOrganizationIdSettingsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV3OrganizationsOrganizationIdSettingsRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV3OrganizationsOrganizationIdSettingsRequest' from JSON`,
  );
}
