/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PutV3OrdersIdRequest = {
  id: number;
  /**
   * Optional organization Id. Will be required in API version 4.
   */
  eventurasOrgId?: number | undefined;
  orderUpdateRequestDto?: components.OrderUpdateRequestDto | undefined;
};

/** @internal */
export const PutV3OrdersIdRequest$inboundSchema: z.ZodType<
  PutV3OrdersIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  "Eventuras-Org-Id": z.number().int().optional(),
  OrderUpdateRequestDto: components.OrderUpdateRequestDto$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Eventuras-Org-Id": "eventurasOrgId",
    "OrderUpdateRequestDto": "orderUpdateRequestDto",
  });
});

/** @internal */
export type PutV3OrdersIdRequest$Outbound = {
  id: number;
  "Eventuras-Org-Id"?: number | undefined;
  OrderUpdateRequestDto?: components.OrderUpdateRequestDto$Outbound | undefined;
};

/** @internal */
export const PutV3OrdersIdRequest$outboundSchema: z.ZodType<
  PutV3OrdersIdRequest$Outbound,
  z.ZodTypeDef,
  PutV3OrdersIdRequest
> = z.object({
  id: z.number().int(),
  eventurasOrgId: z.number().int().optional(),
  orderUpdateRequestDto: components.OrderUpdateRequestDto$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    eventurasOrgId: "Eventuras-Org-Id",
    orderUpdateRequestDto: "OrderUpdateRequestDto",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutV3OrdersIdRequest$ {
  /** @deprecated use `PutV3OrdersIdRequest$inboundSchema` instead. */
  export const inboundSchema = PutV3OrdersIdRequest$inboundSchema;
  /** @deprecated use `PutV3OrdersIdRequest$outboundSchema` instead. */
  export const outboundSchema = PutV3OrdersIdRequest$outboundSchema;
  /** @deprecated use `PutV3OrdersIdRequest$Outbound` instead. */
  export type Outbound = PutV3OrdersIdRequest$Outbound;
}

export function putV3OrdersIdRequestToJSON(
  putV3OrdersIdRequest: PutV3OrdersIdRequest,
): string {
  return JSON.stringify(
    PutV3OrdersIdRequest$outboundSchema.parse(putV3OrdersIdRequest),
  );
}

export function putV3OrdersIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PutV3OrdersIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV3OrdersIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV3OrdersIdRequest' from JSON`,
  );
}
