/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ProductVisibility = {
  Event: "Event",
  Collection: "Collection",
} as const;
export type ProductVisibility = ClosedEnum<typeof ProductVisibility>;

/** @internal */
export const ProductVisibility$inboundSchema: z.ZodNativeEnum<
  typeof ProductVisibility
> = z.nativeEnum(ProductVisibility);

/** @internal */
export const ProductVisibility$outboundSchema: z.ZodNativeEnum<
  typeof ProductVisibility
> = ProductVisibility$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductVisibility$ {
  /** @deprecated use `ProductVisibility$inboundSchema` instead. */
  export const inboundSchema = ProductVisibility$inboundSchema;
  /** @deprecated use `ProductVisibility$outboundSchema` instead. */
  export const outboundSchema = ProductVisibility$outboundSchema;
}
