/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const UserListOrder = {
  GivenName: "GivenName",
  FamilyName: "FamilyName",
  Email: "Email",
  Phone: "Phone",
} as const;
export type UserListOrder = ClosedEnum<typeof UserListOrder>;

/** @internal */
export const UserListOrder$inboundSchema: z.ZodNativeEnum<
  typeof UserListOrder
> = z.nativeEnum(UserListOrder);

/** @internal */
export const UserListOrder$outboundSchema: z.ZodNativeEnum<
  typeof UserListOrder
> = UserListOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserListOrder$ {
  /** @deprecated use `UserListOrder$inboundSchema` instead. */
  export const inboundSchema = UserListOrder$inboundSchema;
  /** @deprecated use `UserListOrder$outboundSchema` instead. */
  export const outboundSchema = UserListOrder$outboundSchema;
}
