version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
        VARIANT: 5.0
        # Options
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        INSTALL_AZURE_CLI: "false"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5433;Database=eventuras_db;Username=pguser;Password=Str0ng!PaSsw0rd

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

  postgres:
    image: "postgres"
    container_name: "devcontainer_postgres"
    environment:
      - POSTGRES_DB=eventuras_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=Str0ng!PaSsw0rd
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - "5433:5432"

volumes:
  postgres_data:
