{{- if .Values.networkPolicy.enabled }}
# Only allow ingress to BuildKit from runner pods in arc-runners namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: buildkit-allow-runners
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: arc-runners
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
{{- end }}
