apiVersion: v2
name: arc-controller
description: Actions Runner Controller (ARC) v2 - Controller
type: application
version: 0.1.0
appVersion: "0.11.0"

dependencies:
  - name: gha-runner-scale-set-controller
    version: "0.11.0"
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
