/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Certificates } from "./certificates.js";
import { EventCertificates } from "./eventcertificates.js";
import { EventCollection } from "./eventcollection.js";
import { EventCollectionMapping } from "./eventcollectionmapping.js";
import { EventProducts } from "./eventproducts.js";
import { EventProductVariants } from "./eventproductvariants.js";
import { Events } from "./events.js";
import { EventStatistics } from "./eventstatistics.js";
import { Invoices } from "./invoices.js";
import { NotificationRecipients } from "./notificationrecipients.js";
import { Notifications } from "./notifications.js";
import { NotificationsQueueing } from "./notificationsqueueing.js";
import { OnlineCourse } from "./onlinecourse.js";
import { Orders } from "./orders.js";
import { OrganizationMemberRoles } from "./organizationmemberroles.js";
import { OrganizationMembers } from "./organizationmembers.js";
import { Organizations } from "./organizations.js";
import { OrganizationSettings } from "./organizationsettings.js";
import { Products } from "./products.js";
import { RegistrationCertificate } from "./registrationcertificate.js";
import { RegistrationOrders } from "./registrationorders.js";
import { Registrations } from "./registrations.js";
import { UserProfile } from "./userprofile.js";
import { Users } from "./users.js";

export class EventurasSDK extends ClientSDK {
  private _certificates?: Certificates;
  get certificates(): Certificates {
    return (this._certificates ??= new Certificates(this._options));
  }

  private _eventCertificates?: EventCertificates;
  get eventCertificates(): EventCertificates {
    return (this._eventCertificates ??= new EventCertificates(this._options));
  }

  private _eventCollection?: EventCollection;
  get eventCollection(): EventCollection {
    return (this._eventCollection ??= new EventCollection(this._options));
  }

  private _eventCollectionMapping?: EventCollectionMapping;
  get eventCollectionMapping(): EventCollectionMapping {
    return (this._eventCollectionMapping ??= new EventCollectionMapping(
      this._options,
    ));
  }

  private _eventProducts?: EventProducts;
  get eventProducts(): EventProducts {
    return (this._eventProducts ??= new EventProducts(this._options));
  }

  private _eventProductVariants?: EventProductVariants;
  get eventProductVariants(): EventProductVariants {
    return (this._eventProductVariants ??= new EventProductVariants(
      this._options,
    ));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _eventStatistics?: EventStatistics;
  get eventStatistics(): EventStatistics {
    return (this._eventStatistics ??= new EventStatistics(this._options));
  }

  private _invoices?: Invoices;
  get invoices(): Invoices {
    return (this._invoices ??= new Invoices(this._options));
  }

  private _notificationRecipients?: NotificationRecipients;
  get notificationRecipients(): NotificationRecipients {
    return (this._notificationRecipients ??= new NotificationRecipients(
      this._options,
    ));
  }

  private _notifications?: Notifications;
  get notifications(): Notifications {
    return (this._notifications ??= new Notifications(this._options));
  }

  private _notificationsQueueing?: NotificationsQueueing;
  get notificationsQueueing(): NotificationsQueueing {
    return (this._notificationsQueueing ??= new NotificationsQueueing(
      this._options,
    ));
  }

  private _onlineCourse?: OnlineCourse;
  get onlineCourse(): OnlineCourse {
    return (this._onlineCourse ??= new OnlineCourse(this._options));
  }

  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }

  private _organizationMemberRoles?: OrganizationMemberRoles;
  get organizationMemberRoles(): OrganizationMemberRoles {
    return (this._organizationMemberRoles ??= new OrganizationMemberRoles(
      this._options,
    ));
  }

  private _organizationMembers?: OrganizationMembers;
  get organizationMembers(): OrganizationMembers {
    return (this._organizationMembers ??= new OrganizationMembers(
      this._options,
    ));
  }

  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }

  private _organizationSettings?: OrganizationSettings;
  get organizationSettings(): OrganizationSettings {
    return (this._organizationSettings ??= new OrganizationSettings(
      this._options,
    ));
  }

  private _products?: Products;
  get products(): Products {
    return (this._products ??= new Products(this._options));
  }

  private _registrationCertificate?: RegistrationCertificate;
  get registrationCertificate(): RegistrationCertificate {
    return (this._registrationCertificate ??= new RegistrationCertificate(
      this._options,
    ));
  }

  private _registrationOrders?: RegistrationOrders;
  get registrationOrders(): RegistrationOrders {
    return (this._registrationOrders ??= new RegistrationOrders(this._options));
  }

  private _registrations?: Registrations;
  get registrations(): Registrations {
    return (this._registrations ??= new Registrations(this._options));
  }

  private _userProfile?: UserProfile;
  get userProfile(): UserProfile {
    return (this._userProfile ??= new UserProfile(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }
}
