get:
  summary: Get event products list.
  operationId: getEventProductsList
  tags:
    - events
    - products
  parameters:
    - name: id
      in: path
      description: Event ID.
      required: true
      schema:
        type: integer
        format: int32
    - name: visibility
      in: query
      description: |
        Product visibility level.
        Set to `collection` to include all products which visibility is set to `event` or `collection`,
        or set to `event` (default) to only return products visible within a single event.
      required: false
      schema:
        $ref: '../../schemas/events/ProductVisibility.yaml'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/events/ProductDto.yaml'
    '400':
      $ref: 'eventuras-api.v3.yaml#/components/responses/InvalidRequestError'
    '404':
      $ref: 'eventuras-api.v3.yaml#/components/responses/NotFound'
    '500':
      $ref: 'eventuras-api.v3.yaml#/components/responses/InternalServerError'

post:
  summary: Add product to event.
  operationId: addProductToEvent
  tags:
    - events
    - products
  parameters:
    - name: id
      in: path
      description: Event ID.
      required: true
      schema:
        type: integer
        format: int32
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/events/NewProductDto.yaml'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../schemas/events/ProductDto.yaml'
    '400':
      $ref: 'eventuras-api.v3.yaml#/components/responses/InvalidRequestError'
    '401':
      $ref: 'eventuras-api.v3.yaml#/components/responses/UnauthorizedError'
    '403':
      $ref: 'eventuras-api.v3.yaml#/components/responses/ForbiddenError'
    '404':
      $ref: 'eventuras-api.v3.yaml#/components/responses/NotFound'
    '500':
      $ref: 'eventuras-api.v3.yaml#/components/responses/InternalServerError'
