/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventCollectionMappingDeleteV3EventsEventIdCollectionsCollectionId } from "../funcs/eventCollectionMappingDeleteV3EventsEventIdCollectionsCollectionId.js";
import { eventCollectionMappingPutV3EventsEventIdCollectionsCollectionId } from "../funcs/eventCollectionMappingPutV3EventsEventIdCollectionsCollectionId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EventCollectionMapping extends ClientSDK {
  async putV3EventsEventIdCollectionsCollectionId(
    request: operations.PutV3EventsEventIdCollectionsCollectionIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      eventCollectionMappingPutV3EventsEventIdCollectionsCollectionId(
        this,
        request,
        options,
      ),
    );
  }

  async deleteV3EventsEventIdCollectionsCollectionId(
    request: operations.DeleteV3EventsEventIdCollectionsCollectionIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      eventCollectionMappingDeleteV3EventsEventIdCollectionsCollectionId(
        this,
        request,
        options,
      ),
    );
  }
}
