/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationMembersDeleteV3OrganizationsOrganizationIdMembersUserId } from "../funcs/organizationMembersDeleteV3OrganizationsOrganizationIdMembersUserId.js";
import { organizationMembersPutV3OrganizationsOrganizationIdMembersUserId } from "../funcs/organizationMembersPutV3OrganizationsOrganizationIdMembersUserId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class OrganizationMembers extends ClientSDK {
  async putV3OrganizationsOrganizationIdMembersUserId(
    request: operations.PutV3OrganizationsOrganizationIdMembersUserIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      organizationMembersPutV3OrganizationsOrganizationIdMembersUserId(
        this,
        request,
        options,
      ),
    );
  }

  async deleteV3OrganizationsOrganizationIdMembersUserId(
    request: operations.DeleteV3OrganizationsOrganizationIdMembersUserIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      organizationMembersDeleteV3OrganizationsOrganizationIdMembersUserId(
        this,
        request,
        options,
      ),
    );
  }
}
