/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  DeleteV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum,
  organizationMemberRolesDeleteV3OrganizationsOrganizationIdMembersUserIdRoles,
} from "../funcs/organizationMemberRolesDeleteV3OrganizationsOrganizationIdMembersUserIdRoles.js";
import {
  GetV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum,
  organizationMemberRolesGetV3OrganizationsOrganizationIdMembersUserIdRoles,
} from "../funcs/organizationMemberRolesGetV3OrganizationsOrganizationIdMembersUserIdRoles.js";
import {
  organizationMemberRolesPostV3OrganizationsOrganizationIdMembersUserIdRoles,
  PostV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum,
} from "../funcs/organizationMemberRolesPostV3OrganizationsOrganizationIdMembersUserIdRoles.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum } from "../funcs/organizationMemberRolesGetV3OrganizationsOrganizationIdMembersUserIdRoles.js";

export { PostV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum } from "../funcs/organizationMemberRolesPostV3OrganizationsOrganizationIdMembersUserIdRoles.js";

export { DeleteV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum } from "../funcs/organizationMemberRolesDeleteV3OrganizationsOrganizationIdMembersUserIdRoles.js";

export class OrganizationMemberRoles extends ClientSDK {
  async getV3OrganizationsOrganizationIdMembersUserIdRoles(
    request:
      operations.GetV3OrganizationsOrganizationIdMembersUserIdRolesRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?:
        GetV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum;
    },
  ): Promise<
    operations.GetV3OrganizationsOrganizationIdMembersUserIdRolesResponse
  > {
    return unwrapAsync(
      organizationMemberRolesGetV3OrganizationsOrganizationIdMembersUserIdRoles(
        this,
        request,
        options,
      ),
    );
  }

  async postV3OrganizationsOrganizationIdMembersUserIdRoles(
    request:
      operations.PostV3OrganizationsOrganizationIdMembersUserIdRolesRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?:
        PostV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum;
    },
  ): Promise<
    operations.PostV3OrganizationsOrganizationIdMembersUserIdRolesResponse
  > {
    return unwrapAsync(
      organizationMemberRolesPostV3OrganizationsOrganizationIdMembersUserIdRoles(
        this,
        request,
        options,
      ),
    );
  }

  async deleteV3OrganizationsOrganizationIdMembersUserIdRoles(
    request:
      operations.DeleteV3OrganizationsOrganizationIdMembersUserIdRolesRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?:
        DeleteV3OrganizationsOrganizationIdMembersUserIdRolesAcceptEnum;
    },
  ): Promise<
    operations.DeleteV3OrganizationsOrganizationIdMembersUserIdRolesResponse
  > {
    return unwrapAsync(
      organizationMemberRolesDeleteV3OrganizationsOrganizationIdMembersUserIdRoles(
        this,
        request,
        options,
      ),
    );
  }
}
