/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  GetV3ProductsProductIdSummaryAcceptEnum,
  productsGetV3ProductsProductIdSummary,
} from "../funcs/productsGetV3ProductsProductIdSummary.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetV3ProductsProductIdSummaryAcceptEnum } from "../funcs/productsGetV3ProductsProductIdSummary.js";

export class Products extends ClientSDK {
  async getV3ProductsProductIdSummary(
    request: operations.GetV3ProductsProductIdSummaryRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: GetV3ProductsProductIdSummaryAcceptEnum;
    },
  ): Promise<operations.GetV3ProductsProductIdSummaryResponse> {
    return unwrapAsync(productsGetV3ProductsProductIdSummary(
      this,
      request,
      options,
    ));
  }
}
