/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { registrationCertificatePostV3RegistrationsIdCertificateSend } from "../funcs/registrationCertificatePostV3RegistrationsIdCertificateSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class RegistrationCertificate extends ClientSDK {
  async postV3RegistrationsIdCertificateSend(
    request: operations.PostV3RegistrationsIdCertificateSendRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      registrationCertificatePostV3RegistrationsIdCertificateSend(
        this,
        request,
        options,
      ),
    );
  }
}
