type: object
title: Product data.
required:
  - productId
  - name
  - description
  - price
  - variants
properties:
  productId:
    type: integer
    format: int32
  name:
    type: string
    description: Product name.
  description:
    type: string
    description: Product description.
  more:
    type: string
    description: More information about the product.
  price:
    type: number
    format: float
  vatPercent:
    type: number
    format: float
  variants:
    type: array
    items:
      $ref: './ProductVariantDto.yaml'
  visibility:
    $ref: './ProductVisibility.yaml'
example:
  productId: 1001
  name: Test Product
  description: Test
  more: More on this product...
  price: 19.99
  vatPercent: 17
  variants:
    - productVariantId: 34
      name: Red Coloured Test Product
      description: Some variant description...
      price: 21.99
    - productVariantId: 35
      name: Green Coloured Test Product
      description: Some variant description...
      price: 22.99
  visibility: event

