type: object
title: Product variant data.
required:
  - productVariantId
  - name
  - description
  - price
properties:
  productVariantId:
    type: integer
    format: int32
  name:
    type: string
    description: Product variant name.
  description:
    type: string
    description: Product variant description.
  price:
    type: number
    format: float
  vatPercent:
    type: number
    format: int32
example:
  productVariantId: 34
  name: Red Coloured Test Product
  description: Some variant description...
  price: 21.99
