name: Release

on:
  release:
    types:
      - published

env:
  ORGANIZATION_NAME: losolio
  IMAGE_NAME: eventuras

jobs:
  build:
    uses: ./.github/workflows/api-build.yml

  docker:
    name: Build and push Docker image
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    environment: api-prod

    steps:
      - name: Deploy to Azure App Service
        id: deploy-to-azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
