name: API CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  format:
    name: dotnet format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api/
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: '10.x'
      - name: dotnet format
        run: dotnet format --verify-no-changes

  build:
    name: Build project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api/
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: '10.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore -o ./Release

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./apps/api/
    strategy:
      matrix:
        test_set:
          - name: "Unit Tests"
            path: "./tests/Eventuras.UnitTests/Eventuras.UnitTests.csproj"
          - name: "Web API Integration Tests"
            path: "./tests/Eventuras.WebApi.Tests/Eventuras.WebApi.Tests.csproj"
          - name: "Services Integration Tests"
            path: "./tests/Eventuras.Services.Tests/Eventuras.Services.Tests.csproj"
          - name: "Converto Service Tests"
            path: "./tests/Eventuras.Services.Converto.Tests/Eventuras.Services.Converto.Tests.csproj"
          - name: "Email Communication Tests"
            path: "./tests/Losol.Communication.Email.Tests/Losol.Communication.Email.Tests.csproj"
    name: ${{ matrix.test_set.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: '10.x'
      - name: Run tests
        run: dotnet test --project ${{ matrix.test_set.path }}
