name: Release - ConvertoApi docker image

on:
  workflow_dispatch:

env:
  ORGANIZATION_NAME: losolio
  IMAGE_NAME: converto-api

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

      - name: Set Docker Tag
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:$(date +'%Y%m%d-%H%M%S')-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ConvertoApi
          push: true
