name: "Scribo: Deploy site"

on:
  push:
    branches:
      - main
    paths:
      - "libs/scribo/**"
  workflow_dispatch:

jobs:
  publish:
    name: "Scribo: Publish site"
    runs-on: ubuntu-latest
    environment: scribo
    permissions:
      contents: read
      deployments: write
    defaults:
      run:
        working-directory: ./libs/scribo

    steps:
      - uses: actions/checkout@v4

      # ✅ Setup Node.js from .nvmrc
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          check-latest: true
          cache: "npm"

      # Show versions for debugging
      - run: node -v && npm -v

      # ✅ Install dependencies
      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Build site
        run: npm run build:site

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: scribo
          directory: libs/scribo/dist/site
          wranglerVersion: "3"
