name: Release - Deploy

on:
  release:
    types: [published]

env:
  ORGANIZATION_NAME: losolio
  IMAGE_NAME: eventuras

jobs:
  build-api:
    uses: ./.github/workflows/main-api.yml

  docker:
    name: API - Docker image
    needs: build-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api/
          push: true
          tags: ${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}

  deploy-api:
    runs-on: ubuntu-latest
    needs: docker
    environment: api-prod

    steps:
      - name: Deploy API to production
        id: deploy-to-azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}

  deploy-web-prod-1:
    uses: ./.github/workflows/util-vercel-deploy.yml
    with:
      environment: "web-prod-1"
      vercel_environment: "production"
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

  deploy-web-prod-2:
    uses: ./.github/workflows/util-vercel-deploy.yml
    with:
      environment: "web-prod-2"
      vercel_environment: "production"
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
