name: Release - ConvertoApi docker image

on:
  workflow_dispatch:

env:
  DOCKER_ORG: losolio
  DOCKER_IMAGE: converto-api
  DOCKER_FILE: Dockerfile.ConvertoApi

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file ${{ env.DOCKER_FILE }}
          fi

      - name: Set Docker Tag
        run: echo "DOCKER_TAG=${{ env.DOCKER_ORG }}/${{ env.DOCKER_IMAGE }}:$(date +'%Y%m%d-%H%M%S')-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          tags: ${{ env.DOCKER_TAG }}
          push: true
