name: "Docsite: deploy"

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  docs-deploy:
    uses: ./.github/workflows/util-vercel-deploy.yml
    with:
      environment: "docsite"
    secrets: inherit
