name: "Docsite: deploy"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  Deploy-Docs:
    runs-on: ubuntu-latest
    environment: docsite
    steps:
      - uses: ./.github/workflows/util-vercel-deploy.yml
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          environment: "production"
          promote: true
