name: "Docsite: deploy"

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  docs-deploy:
    uses: ./.github/workflows/util-vercel-deploy.yml
    with:
      environment: docsite
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
