name: .NET build & test

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        default: "7"
        type: string
  push:
    paths:
      - "src/**"
      - "tests/**"

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test_set:
          - name: "Unit Tests"
            path: "./tests/Eventuras.UnitTests/Eventuras.UnitTests.csproj"
          - name: "Web API Integration Tests"
            path: "./tests/Eventuras.WebApi.Tests/Eventuras.WebApi.Tests.csproj"
    name: ${{ matrix.test_set.name }}
    steps:
      - uses: actions/checkout@v4
        name: Setup dotnet
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - run: dotnet test ${{ matrix.test_set.path }}
