name: Latest

on:
  push:
    branches:
      - fix/dci

env:
  ORGANIZATION_NAME: losolio
  IMAGE_NAME: eventuras
  AZURE_WEBAPP_NAME: eventuras

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml

  docker:
    name: Build and push Docker image
    needs: build
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ env.DOCKER_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker Tag
        run: echo "DOCKER_TAG=${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAG }}

      - name: Output Docker tag
        run: echo "Docker tag is ${{ env.DOCKER_TAG }}"

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure App Service
        id: deploy-to-azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ needs.docker.outputs.docker_tag }}
