name: Historia CMS CI

on:
  push:
    branches:
      - main
    paths:
      - "apps/historia/**"
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - "apps/historia/**"

env:
  ORGANIZATION_NAME: losolio
  IMAGE_NAME: historia

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set-docker-tag.outputs.docker_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile.Historia
          fi

      - name: Set Docker Tag
        id: set-docker-tag
        run: |
          GIT_COMMIT=${{ github.sha }}
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "docker_tag=${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:main-$(date +'%Y%m%d-%H%M%S')-${GIT_COMMIT::8}" >> $GITHUB_ENV
          else
            echo "docker_tag=${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:canary-$(date +'%Y%m%d-%H%M%S')-${GIT_COMMIT::8}" >> $GITHUB_ENV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.Historia
          push: true
          tags: ${{ env.docker_tag }}

      - name: Output Docker tag
        run: echo "Docker tag is ${{ env.docker_tag }}"
