name: Eventuras CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  commitlint:
    uses: ./.github/workflows/util-commitlint.yml
    with:
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      node_version: "22.x"
