name: idem-idp • docker build & push (Docker Hub)

on:
  push:
    branches: [ main, feature/**, feat/**, fix/**, bugfix/**, chore/**, release/** ]
    paths:
      - "apps/idem-idp/**"
  pull_request:
    branches: [ main ]
    paths:
      - "apps/idem-idp/**"


env:
  ORG: losolio
  IMAGE_NAME: idem-idp
  TURBO_VERSION: 2.5.8

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix: { platform: [ linux/amd64, linux/arm64 ] }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Compute version: tag -> strip "v"; else read package.json
      - name: Compute version
        id: ver
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            V="${GITHUB_REF#refs/tags/v}"
          else
            V=$(node -p "require('./apps/idem-idp/package.json').version")
          fi
          echo "version=$V" >> "$GITHUB_OUTPUT"
          echo "sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ORG }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=ref,event=tag
          labels: |
            org.opencontainers.image.version=${{ steps.ver.outputs.version }}
            org.opencontainers.image.revision=${{ steps.ver.outputs.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/idem-idp/Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            TURBO_VERSION=${{ env.TURBO_VERSION }}
            APP_VERSION=${{ steps.ver.outputs.version }}
            GIT_SHA=${{ steps.ver.outputs.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
