on:
  push:
    paths:
      - "./libs/scribo/**"

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    environment: scribo
    permissions:
      contents: read
      deployments: write
    defaults:
      run:
        working-directory: ./libs/scribo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build site
        run: npm run build:site
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: scribo
          directory: libs/scribo/dist/site
          wranglerVersion: "3"
