name: Deploy main branch to staging environment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
jobs:
  Deploy-Staging:
    environment: web-staging
    defaults:
      run:
        working-directory: apps/web
    runs-on: ubuntu-latest
    steps:
      # We are using a separate site for staging, so this is set as production on Vercel
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Promote staging as demo production site
        run: vercel promote --token=${{ secrets.VERCEL_TOKEN }}
