name: Web
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    paths:
      - "apps/web/**"
      - "libs/**"
  workflow_call:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/util-web-build.yml
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
