name: Web
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "libs/**"
  workflow_call:

jobs:
  deploy-preview:
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/util-vercel-deploy.yml
    with:
      environment: web-dev
      url: dev.eventuras.losol.io
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
